function checkToolboxes(required)
    % Key: cell array of char (not string) to avoid containers.Map error
    keys = { ...
        'Simulink', ...
        'Phased Array System Toolbox', ...
        'DSP System Toolbox', ...
        'Radar Toolbox', ...
        'Image Processing Toolbox', ...
        'Simulink 3D Animation', ...
        'Lidar Toolbox', ...
        'Navigation Toolbox', ...
        'Sensor Fusion and Tracking Toolbox', ...
        'Signal Processing Toolbox', ...
        'UAV Toolbox', ...
        'Computer Vision Toolbox' ...
        };

    values = { ...
        'SL', 'AR', 'DS', 'RA', 'IP', 'VR', ...
        'LP', 'NV', 'TF', 'SG', 'UV', 'VP' ...
        };

    nameToId = containers.Map(keys, values);

    installed = matlab.addons.installedAddons;
    installedNames = string(installed.Name);

    flag = false;
    for i = 1:length(required)
        rname = required(i);
        if ~any(installedNames == rname)
            if isKey(nameToId, char(rname))
                rid = nameToId(char(rname));
                link = sprintf( ...
                    "<a href=""matlab:matlab.internal.addons.launchers.showExplorer('ErrorRecovery', 'identifier', '%s', 'focused', 'addon')"">%s</a>\n", ...
                    rid, rname);
                fprintf("Missing toolbox: %s", link);
            else
                fprintf("Missing toolbox: %s\n", rname);
            end
            flag = true;
        end
    end

    if flag
        error("Missing toolbox(es).");
    end
end
